AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/environments/*
    - bin/**/*

Rails:
  Enabled: true

# Disables "Use nested module/class definitions instead of compact style" warning
ClassAndModuleChildren:
  Enabled: false

# 15 is too low, but 20 seems like a good goal for us
Metrics/AbcSize:
  Max: 20

# 80 is too low, but 250 seems like a good goal for us
Metrics/LineLength:
  Max: 120

# 10 is too low, but 15 seems like a good goal for us
Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 120

# Disables "Missing top-level class documentation comment" warning
Documentation:
<<<<<<< HEAD
  Enabled: false
=======
  Enabled: false
>>>>>>> general fixes
